weights: ./runs/train/exp12/weights/last.pt
cfg: ''
data: data/plate.yaml
hyp: data/hyp.scratch.tiny.yaml
epochs: 80
batch_size: 32
img_size:
- 512
- 2048
rect: false
resume: true
nosave: false
notest: false
noautoanchor: true
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 32
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
freeze:
- 0
v5_metric: false
plate_style: realrandom
world_size: 1
global_rank: -1
save_dir: runs/train/exp12
total_batch_size: 32
